version: '3.7'

services:
  web:
    build: .
    command: gunicorn dockerproject.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.dev
    ports:
    - 8000:8000
    depends_on:
      - db

  db:
    image: library/postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=docker_django

volumes:
  postgres_data: