name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_ALLOWED_HOSTS: '127.0.0.1'
      SECRET_KEY: 'cdjsjcodsidcsSDCZE435346FVDVDfvdfvdth756'
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
        PATH="$HOME/.poetry/bin:$PATH"
        source $HOME/.poetry/env
        poetry install --no-dev
    - name: Run Tests
      run: |
        source $HOME/.poetry/env
        poetry run python src/manage.py test
