name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DJANGO_ALLOWED_HOSTS: '127.0.0.1'
  SECRET_KEY: 'cdjsjcodsidcsSDCZE435346FVDVDfvdfvdth756'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
        PATH="$HOME/.poetry/bin:$PATH"
        source $HOME/.poetry/env
        poetry install --no-dev
    - name: Run Tests
      run: |
        source $HOME/.poetry/env
        poetry run python src/manage.py test


  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
              DJANGO_ALLOWED_HOSTS='127.0.0.1'
              SECRET_KEY='cdjsjcodsidcsSDCZE435346FVDVDfvdfvdth756'
          platforms: linux/arm64
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0
            ghcr.io/user/app:latest
            ghcr.io/user/app:1.0.0
